"""Built-in food nutrition database for Daily Chow.

Each entry stores macros per 100g and sensible default bounds (grams).
Keys are stable slugs used in state persistence; display names are separate.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Food:
    name: str
    unit_note: str  # e.g. "dry", "raw", "cooked"
    cal_per_100g: float
    protein_per_100g: float
    fat_per_100g: float
    carbs_per_100g: float
    fiber_per_100g: float
    category: str
    default_min: int = 0
    default_max: int = 500


# ── Database ──────────────────────────────────────────────────────────

FOODS: dict[str, Food] = {
    # ── Grains ────────────────────────────────────────────────────────
    "white_rice_dry": Food(
        name="White rice",
        unit_note="dry",
        cal_per_100g=365,
        protein_per_100g=7.0,
        fat_per_100g=0.6,
        carbs_per_100g=80.0,
        fiber_per_100g=1.0,
        category="grains",
        default_min=0,
        default_max=400,
    ),
    "brown_rice_dry": Food(
        name="Brown rice",
        unit_note="dry",
        cal_per_100g=370,
        protein_per_100g=7.9,
        fat_per_100g=2.9,
        carbs_per_100g=77.0,
        fiber_per_100g=3.5,
        category="grains",
        default_min=0,
        default_max=400,
    ),
    "oats_dry": Food(
        name="Oats",
        unit_note="dry",
        cal_per_100g=389,
        protein_per_100g=16.9,
        fat_per_100g=6.9,
        carbs_per_100g=66.0,
        fiber_per_100g=10.6,
        category="grains",
        default_min=0,
        default_max=300,
    ),
    "quinoa_dry": Food(
        name="Quinoa",
        unit_note="dry",
        cal_per_100g=368,
        protein_per_100g=14.1,
        fat_per_100g=6.1,
        carbs_per_100g=64.0,
        fiber_per_100g=7.0,
        category="grains",
        default_min=0,
        default_max=300,
    ),
    "pasta_dry": Food(
        name="Pasta",
        unit_note="dry",
        cal_per_100g=371,
        protein_per_100g=13.0,
        fat_per_100g=1.5,
        carbs_per_100g=75.0,
        fiber_per_100g=1.8,
        category="grains",
        default_min=0,
        default_max=400,
    ),
    "bread_whole_wheat": Food(
        name="Whole wheat bread",
        unit_note="sliced",
        cal_per_100g=247,
        protein_per_100g=13.0,
        fat_per_100g=3.4,
        carbs_per_100g=41.0,
        fiber_per_100g=6.8,
        category="grains",
        default_min=0,
        default_max=300,
    ),
    "corn_tortilla": Food(
        name="Corn tortilla",
        unit_note="—",
        cal_per_100g=218,
        protein_per_100g=5.7,
        fat_per_100g=2.8,
        carbs_per_100g=44.0,
        fiber_per_100g=5.2,
        category="grains",
        default_min=0,
        default_max=300,
    ),
    "sweet_potato_raw": Food(
        name="Sweet potato",
        unit_note="raw",
        cal_per_100g=86,
        protein_per_100g=1.6,
        fat_per_100g=0.1,
        carbs_per_100g=20.0,
        fiber_per_100g=3.0,
        category="grains",
        default_min=0,
        default_max=500,
    ),
    "potato_raw": Food(
        name="Potato",
        unit_note="raw",
        cal_per_100g=77,
        protein_per_100g=2.0,
        fat_per_100g=0.1,
        carbs_per_100g=17.0,
        fiber_per_100g=2.2,
        category="grains",
        default_min=0,
        default_max=500,
    ),
    # ── Vegetables ────────────────────────────────────────────────────
    "broccoli_raw": Food(
        name="Broccoli",
        unit_note="raw",
        cal_per_100g=34,
        protein_per_100g=2.8,
        fat_per_100g=0.4,
        carbs_per_100g=7.0,
        fiber_per_100g=2.6,
        category="vegetables",
        default_min=0,
        default_max=400,
    ),
    "carrots_raw": Food(
        name="Carrots",
        unit_note="raw",
        cal_per_100g=41,
        protein_per_100g=0.9,
        fat_per_100g=0.2,
        carbs_per_100g=10.0,
        fiber_per_100g=2.8,
        category="vegetables",
        default_min=0,
        default_max=300,
    ),
    "zucchini_raw": Food(
        name="Zucchini",
        unit_note="raw",
        cal_per_100g=17,
        protein_per_100g=1.2,
        fat_per_100g=0.3,
        carbs_per_100g=3.1,
        fiber_per_100g=1.0,
        category="vegetables",
        default_min=0,
        default_max=500,
    ),
    "spinach_raw": Food(
        name="Spinach",
        unit_note="raw",
        cal_per_100g=23,
        protein_per_100g=2.9,
        fat_per_100g=0.4,
        carbs_per_100g=3.6,
        fiber_per_100g=2.2,
        category="vegetables",
        default_min=0,
        default_max=300,
    ),
    "kale_raw": Food(
        name="Kale",
        unit_note="raw",
        cal_per_100g=49,
        protein_per_100g=4.3,
        fat_per_100g=0.9,
        carbs_per_100g=9.0,
        fiber_per_100g=3.6,
        category="vegetables",
        default_min=0,
        default_max=300,
    ),
    "bell_pepper_raw": Food(
        name="Bell pepper",
        unit_note="raw",
        cal_per_100g=31,
        protein_per_100g=1.0,
        fat_per_100g=0.3,
        carbs_per_100g=6.0,
        fiber_per_100g=2.1,
        category="vegetables",
        default_min=0,
        default_max=400,
    ),
    "tomato_raw": Food(
        name="Tomato",
        unit_note="raw",
        cal_per_100g=18,
        protein_per_100g=0.9,
        fat_per_100g=0.2,
        carbs_per_100g=3.9,
        fiber_per_100g=1.2,
        category="vegetables",
        default_min=0,
        default_max=500,
    ),
    "onion_raw": Food(
        name="Onion",
        unit_note="raw",
        cal_per_100g=40,
        protein_per_100g=1.1,
        fat_per_100g=0.1,
        carbs_per_100g=9.3,
        fiber_per_100g=1.7,
        category="vegetables",
        default_min=0,
        default_max=300,
    ),
    "cauliflower_raw": Food(
        name="Cauliflower",
        unit_note="raw",
        cal_per_100g=25,
        protein_per_100g=1.9,
        fat_per_100g=0.3,
        carbs_per_100g=5.0,
        fiber_per_100g=2.0,
        category="vegetables",
        default_min=0,
        default_max=400,
    ),
    "cabbage_raw": Food(
        name="Cabbage",
        unit_note="raw",
        cal_per_100g=25,
        protein_per_100g=1.3,
        fat_per_100g=0.1,
        carbs_per_100g=5.8,
        fiber_per_100g=2.5,
        category="vegetables",
        default_min=0,
        default_max=400,
    ),
    "cucumber_raw": Food(
        name="Cucumber",
        unit_note="raw",
        cal_per_100g=15,
        protein_per_100g=0.7,
        fat_per_100g=0.1,
        carbs_per_100g=3.6,
        fiber_per_100g=0.5,
        category="vegetables",
        default_min=0,
        default_max=400,
    ),
    "mushrooms_raw": Food(
        name="Mushrooms",
        unit_note="raw",
        cal_per_100g=22,
        protein_per_100g=3.1,
        fat_per_100g=0.3,
        carbs_per_100g=3.3,
        fiber_per_100g=1.0,
        category="vegetables",
        default_min=0,
        default_max=300,
    ),
    "green_beans_raw": Food(
        name="Green beans",
        unit_note="raw",
        cal_per_100g=31,
        protein_per_100g=1.8,
        fat_per_100g=0.2,
        carbs_per_100g=7.0,
        fiber_per_100g=2.7,
        category="vegetables",
        default_min=0,
        default_max=400,
    ),
    "asparagus_raw": Food(
        name="Asparagus",
        unit_note="raw",
        cal_per_100g=20,
        protein_per_100g=2.2,
        fat_per_100g=0.1,
        carbs_per_100g=3.9,
        fiber_per_100g=2.1,
        category="vegetables",
        default_min=0,
        default_max=400,
    ),
    "brussels_sprouts_raw": Food(
        name="Brussels sprouts",
        unit_note="raw",
        cal_per_100g=43,
        protein_per_100g=3.4,
        fat_per_100g=0.3,
        carbs_per_100g=9.0,
        fiber_per_100g=3.8,
        category="vegetables",
        default_min=0,
        default_max=400,
    ),
    # ── Legumes ───────────────────────────────────────────────────────
    "black_beans_cooked": Food(
        name="Black beans",
        unit_note="cooked",
        cal_per_100g=132,
        protein_per_100g=8.9,
        fat_per_100g=0.5,
        carbs_per_100g=24.0,
        fiber_per_100g=8.7,
        category="legumes",
        default_min=0,
        default_max=400,
    ),
    "yellow_split_peas_dry": Food(
        name="Yellow split peas",
        unit_note="dry",
        cal_per_100g=352,
        protein_per_100g=24.0,
        fat_per_100g=1.2,
        carbs_per_100g=60.0,
        fiber_per_100g=25.0,
        category="legumes",
        default_min=0,
        default_max=150,
    ),
    "lentils_dry": Food(
        name="Lentils",
        unit_note="dry",
        cal_per_100g=352,
        protein_per_100g=24.6,
        fat_per_100g=1.1,
        carbs_per_100g=60.0,
        fiber_per_100g=10.7,
        category="legumes",
        default_min=0,
        default_max=200,
    ),
    "chickpeas_cooked": Food(
        name="Chickpeas",
        unit_note="cooked",
        cal_per_100g=164,
        protein_per_100g=8.9,
        fat_per_100g=2.6,
        carbs_per_100g=27.0,
        fiber_per_100g=7.6,
        category="legumes",
        default_min=0,
        default_max=400,
    ),
    "kidney_beans_cooked": Food(
        name="Kidney beans",
        unit_note="cooked",
        cal_per_100g=127,
        protein_per_100g=8.7,
        fat_per_100g=0.5,
        carbs_per_100g=22.8,
        fiber_per_100g=6.4,
        category="legumes",
        default_min=0,
        default_max=400,
    ),
    "pinto_beans_cooked": Food(
        name="Pinto beans",
        unit_note="cooked",
        cal_per_100g=143,
        protein_per_100g=9.0,
        fat_per_100g=0.6,
        carbs_per_100g=26.0,
        fiber_per_100g=9.0,
        category="legumes",
        default_min=0,
        default_max=400,
    ),
    "edamame_shelled": Food(
        name="Edamame",
        unit_note="shelled",
        cal_per_100g=121,
        protein_per_100g=11.9,
        fat_per_100g=5.2,
        carbs_per_100g=8.9,
        fiber_per_100g=5.2,
        category="legumes",
        default_min=0,
        default_max=400,
    ),
    # ── Meats ─────────────────────────────────────────────────────────
    "ground_beef_80_20_raw": Food(
        name="Ground beef 80/20",
        unit_note="raw",
        cal_per_100g=254,
        protein_per_100g=17.0,
        fat_per_100g=20.0,
        carbs_per_100g=0.0,
        fiber_per_100g=0.0,
        category="meats",
        default_min=0,
        default_max=1000,
    ),
    "ground_beef_90_10_raw": Food(
        name="Ground beef 90/10",
        unit_note="raw",
        cal_per_100g=176,
        protein_per_100g=20.0,
        fat_per_100g=10.0,
        carbs_per_100g=0.0,
        fiber_per_100g=0.0,
        category="meats",
        default_min=0,
        default_max=1000,
    ),
    "chicken_thigh_raw": Food(
        name="Chicken thigh",
        unit_note="raw, boneless skinless",
        cal_per_100g=209,
        protein_per_100g=26.0,
        fat_per_100g=10.9,
        carbs_per_100g=0.0,
        fiber_per_100g=0.0,
        category="meats",
        default_min=0,
        default_max=1000,
    ),
    "chicken_breast_raw": Food(
        name="Chicken breast",
        unit_note="raw, boneless skinless",
        cal_per_100g=120,
        protein_per_100g=22.5,
        fat_per_100g=2.6,
        carbs_per_100g=0.0,
        fiber_per_100g=0.0,
        category="meats",
        default_min=0,
        default_max=1000,
    ),
    "turkey_ground_93_raw": Food(
        name="Ground turkey 93/7",
        unit_note="raw",
        cal_per_100g=150,
        protein_per_100g=19.0,
        fat_per_100g=8.0,
        carbs_per_100g=0.0,
        fiber_per_100g=0.0,
        category="meats",
        default_min=0,
        default_max=1000,
    ),
    "pork_loin_raw": Food(
        name="Pork loin",
        unit_note="raw",
        cal_per_100g=143,
        protein_per_100g=21.0,
        fat_per_100g=5.3,
        carbs_per_100g=0.0,
        fiber_per_100g=0.0,
        category="meats",
        default_min=0,
        default_max=1000,
    ),
    "pork_shoulder_raw": Food(
        name="Pork shoulder",
        unit_note="raw",
        cal_per_100g=236,
        protein_per_100g=16.0,
        fat_per_100g=17.0,
        carbs_per_100g=0.0,
        fiber_per_100g=0.0,
        category="meats",
        default_min=0,
        default_max=1000,
    ),
    "steak_sirloin_raw": Food(
        name="Sirloin steak",
        unit_note="raw",
        cal_per_100g=183,
        protein_per_100g=21.0,
        fat_per_100g=9.3,
        carbs_per_100g=0.0,
        fiber_per_100g=0.0,
        category="meats",
        default_min=0,
        default_max=1000,
    ),
    # ── Seafood ───────────────────────────────────────────────────────
    "salmon_raw": Food(
        name="Salmon",
        unit_note="raw, Atlantic",
        cal_per_100g=208,
        protein_per_100g=20.0,
        fat_per_100g=13.0,
        carbs_per_100g=0.0,
        fiber_per_100g=0.0,
        category="seafood",
        default_min=0,
        default_max=500,
    ),
    "shrimp_raw": Food(
        name="Shrimp",
        unit_note="raw",
        cal_per_100g=85,
        protein_per_100g=20.0,
        fat_per_100g=0.5,
        carbs_per_100g=0.2,
        fiber_per_100g=0.0,
        category="seafood",
        default_min=0,
        default_max=500,
    ),
    "tuna_canned": Food(
        name="Tuna",
        unit_note="canned in water, drained",
        cal_per_100g=116,
        protein_per_100g=25.5,
        fat_per_100g=1.0,
        carbs_per_100g=0.0,
        fiber_per_100g=0.0,
        category="seafood",
        default_min=0,
        default_max=400,
    ),
    "tilapia_raw": Food(
        name="Tilapia",
        unit_note="raw",
        cal_per_100g=96,
        protein_per_100g=20.0,
        fat_per_100g=1.7,
        carbs_per_100g=0.0,
        fiber_per_100g=0.0,
        category="seafood",
        default_min=0,
        default_max=500,
    ),
    "cod_raw": Food(
        name="Cod",
        unit_note="raw",
        cal_per_100g=82,
        protein_per_100g=18.0,
        fat_per_100g=0.7,
        carbs_per_100g=0.0,
        fiber_per_100g=0.0,
        category="seafood",
        default_min=0,
        default_max=500,
    ),
    # ── Oils & Fats ───────────────────────────────────────────────────
    "avocado_oil": Food(
        name="Avocado oil",
        unit_note="—",
        cal_per_100g=884,
        protein_per_100g=0.0,
        fat_per_100g=100.0,
        carbs_per_100g=0.0,
        fiber_per_100g=0.0,
        category="oils_fats",
        default_min=0,
        default_max=100,
    ),
    "olive_oil": Food(
        name="Olive oil",
        unit_note="—",
        cal_per_100g=884,
        protein_per_100g=0.0,
        fat_per_100g=100.0,
        carbs_per_100g=0.0,
        fiber_per_100g=0.0,
        category="oils_fats",
        default_min=0,
        default_max=100,
    ),
    "coconut_oil": Food(
        name="Coconut oil",
        unit_note="—",
        cal_per_100g=862,
        protein_per_100g=0.0,
        fat_per_100g=100.0,
        carbs_per_100g=0.0,
        fiber_per_100g=0.0,
        category="oils_fats",
        default_min=0,
        default_max=100,
    ),
    "butter": Food(
        name="Butter",
        unit_note="—",
        cal_per_100g=717,
        protein_per_100g=0.9,
        fat_per_100g=81.0,
        carbs_per_100g=0.1,
        fiber_per_100g=0.0,
        category="oils_fats",
        default_min=0,
        default_max=100,
    ),
    # ── Dairy ─────────────────────────────────────────────────────────
    "whole_milk": Food(
        name="Whole milk",
        unit_note="—",
        cal_per_100g=61,
        protein_per_100g=3.2,
        fat_per_100g=3.3,
        carbs_per_100g=4.8,
        fiber_per_100g=0.0,
        category="dairy",
        default_min=0,
        default_max=500,
    ),
    "greek_yogurt_whole": Food(
        name="Greek yogurt (whole)",
        unit_note="—",
        cal_per_100g=97,
        protein_per_100g=9.0,
        fat_per_100g=5.0,
        carbs_per_100g=3.6,
        fiber_per_100g=0.0,
        category="dairy",
        default_min=0,
        default_max=500,
    ),
    "cottage_cheese": Food(
        name="Cottage cheese",
        unit_note="2% milkfat",
        cal_per_100g=84,
        protein_per_100g=11.0,
        fat_per_100g=2.3,
        carbs_per_100g=3.4,
        fiber_per_100g=0.0,
        category="dairy",
        default_min=0,
        default_max=500,
    ),
    "cheddar_cheese": Food(
        name="Cheddar cheese",
        unit_note="—",
        cal_per_100g=403,
        protein_per_100g=25.0,
        fat_per_100g=33.0,
        carbs_per_100g=1.3,
        fiber_per_100g=0.0,
        category="dairy",
        default_min=0,
        default_max=200,
    ),
    "eggs_whole": Food(
        name="Eggs",
        unit_note="whole, raw (~50g each)",
        cal_per_100g=143,
        protein_per_100g=12.6,
        fat_per_100g=9.5,
        carbs_per_100g=1.1,
        fiber_per_100g=0.0,
        category="dairy",
        default_min=0,
        default_max=400,
    ),
    # ── Nuts & Seeds ──────────────────────────────────────────────────
    "almonds": Food(
        name="Almonds",
        unit_note="raw",
        cal_per_100g=579,
        protein_per_100g=21.2,
        fat_per_100g=49.0,
        carbs_per_100g=22.0,
        fiber_per_100g=12.5,
        category="nuts_seeds",
        default_min=0,
        default_max=150,
    ),
    "peanut_butter": Food(
        name="Peanut butter",
        unit_note="—",
        cal_per_100g=588,
        protein_per_100g=25.0,
        fat_per_100g=50.0,
        carbs_per_100g=20.0,
        fiber_per_100g=6.0,
        category="nuts_seeds",
        default_min=0,
        default_max=150,
    ),
    "walnuts": Food(
        name="Walnuts",
        unit_note="raw",
        cal_per_100g=654,
        protein_per_100g=15.2,
        fat_per_100g=65.0,
        carbs_per_100g=14.0,
        fiber_per_100g=6.7,
        category="nuts_seeds",
        default_min=0,
        default_max=150,
    ),
    "chia_seeds": Food(
        name="Chia seeds",
        unit_note="—",
        cal_per_100g=486,
        protein_per_100g=17.0,
        fat_per_100g=31.0,
        carbs_per_100g=42.0,
        fiber_per_100g=34.4,
        category="nuts_seeds",
        default_min=0,
        default_max=100,
    ),
    "flax_seeds": Food(
        name="Flax seeds",
        unit_note="ground",
        cal_per_100g=534,
        protein_per_100g=18.3,
        fat_per_100g=42.0,
        carbs_per_100g=29.0,
        fiber_per_100g=27.3,
        category="nuts_seeds",
        default_min=0,
        default_max=100,
    ),
    "hemp_seeds": Food(
        name="Hemp seeds",
        unit_note="hulled",
        cal_per_100g=553,
        protein_per_100g=31.6,
        fat_per_100g=49.0,
        carbs_per_100g=2.8,
        fiber_per_100g=4.0,
        category="nuts_seeds",
        default_min=0,
        default_max=100,
    ),
    # ── Fruits ────────────────────────────────────────────────────────
    "banana": Food(
        name="Banana",
        unit_note="raw",
        cal_per_100g=89,
        protein_per_100g=1.1,
        fat_per_100g=0.3,
        carbs_per_100g=23.0,
        fiber_per_100g=2.6,
        category="fruits",
        default_min=0,
        default_max=400,
    ),
    "apple": Food(
        name="Apple",
        unit_note="raw",
        cal_per_100g=52,
        protein_per_100g=0.3,
        fat_per_100g=0.2,
        carbs_per_100g=14.0,
        fiber_per_100g=2.4,
        category="fruits",
        default_min=0,
        default_max=400,
    ),
    "blueberries": Food(
        name="Blueberries",
        unit_note="raw",
        cal_per_100g=57,
        protein_per_100g=0.7,
        fat_per_100g=0.3,
        carbs_per_100g=14.0,
        fiber_per_100g=2.4,
        category="fruits",
        default_min=0,
        default_max=300,
    ),
    "avocado": Food(
        name="Avocado",
        unit_note="raw",
        cal_per_100g=160,
        protein_per_100g=2.0,
        fat_per_100g=15.0,
        carbs_per_100g=8.5,
        fiber_per_100g=6.7,
        category="fruits",
        default_min=0,
        default_max=300,
    ),
    "dates_medjool": Food(
        name="Medjool dates",
        unit_note="pitted",
        cal_per_100g=277,
        protein_per_100g=1.8,
        fat_per_100g=0.2,
        carbs_per_100g=66.5,
        fiber_per_100g=6.7,
        category="fruits",
        default_min=0,
        default_max=200,
    ),
}


def search(query: str, limit: int = 10) -> list[tuple[str, Food]]:
    """Fuzzy-search foods by name, unit note, or category.

    Returns (key, Food) pairs sorted by match quality.
    Exact prefix matches rank higher than substring matches.
    """
    q = query.lower().strip()
    if not q:
        return []

    prefix_matches: list[tuple[str, Food]] = []
    substring_matches: list[tuple[str, Food]] = []

    for key, food in FOODS.items():
        searchable = f"{food.name} {food.unit_note} {food.category} {key}".lower()
        name_lower = food.name.lower()
        if name_lower.startswith(q):
            prefix_matches.append((key, food))
        elif q in searchable:
            substring_matches.append((key, food))

    return (prefix_matches + substring_matches)[:limit]
